### ISSUE TITLE
Send tab is auto selecting toons from opposite faction

### ISSUE THREAD

**Issue by BristleBeard** [alarofrunetotem/MailCommander#1]
When the Send tab auto populates a toon to send to, it's loading toons that are the opposite faction.

I do not have BoA items set up to send, it's loading requests for normal commodities like cloth.
I do not have the option enabled to show all toons, or toons from the opposite faction.
I cannot see the other faction toons from the dropdown on the Send tab. They only appear from 'auto populating' the next toon to send things.

**Comment by alar77** [comment]
Fixed in 2.0
