### ISSUE TITLE
No longer works since updated from 1.1.6

### ISSUE THREAD

**Issue by RavenDT** [alarofrunetotem/MailCommander#4]
After upgrading from 1.1.6, I received a notice that the database was being migrated?  I let it finish its thing, but since then, MailCommander would no longer send mail.  In fact, many of the times, all my setup appeared blank (e.g. items in inventory that can be sent to alts).  The other day, my settings regarding items being sent to which characters returned, but whenever I click the "Send All" button, the recipient field gets changed to "working" and nothing happens.

I figured since a migration of settings was mentioned, there may have been an overhaul, so I bit the bullet and reset all of my settings.  Now I have a fresh, blank profile.  However, every time I log into a new character, that character is not added to the list of alts.  I also tried manually adding characters, which doesn't work either.  (Characters are on same account, same realm, same faction, above level 30, etc.)

I am currently running v2.0.2 from Curseforge.

**Comment by RavenDT** [comment]
I just tried deleting the addon folder and manually installing from Github, but it was missing the libs folder.  Deleted addon folder again and manually downloaded from Curseforge, but bad behavior still persists.

**Comment by RavenDT** [comment]
Might be an issue with the following change:

In `function addon:loadSelf(level)`

Old code:
```lua
	local p1,p2=GetProfessions()
```
New code (might not be working as intended)
```lua
	local p1,p2=ISCLASSIC and nil,nil or GetProfessions()
```

**Comment by alar77** [comment]
Can you enable lua error and see if something is logged?

**Comment by RavenDT** [comment]
I do have Lua errors enabled, but haven't been getting any.
