### ISSUE TITLE
No characters show up in Need tab if "Show characters from all realms" is unchecked

### ISSUE THREAD

**Issue by syndenbock** [alarofrunetotem/MailCommander#6]
As stated in the title, I need to check said option to have my characters show up in the Need tab to configure items.
This was observed in version 2.0.2.

**Comment by alar77** [comment]
I tried all possible combination, for me it works
![World Of Warcraft - Retail Screenshot 2021 07 11 - 11 00 15 100](https://user-images.githubusercontent.com/19211824/125189227-45f9a780-e237-11eb-8dec-da643f6043a5.png)
![World Of Warcraft - Retail Screenshot 2021 07 11 - 11 01 31 13](https://user-images.githubusercontent.com/19211824/125189253-6e81a180-e237-11eb-9772-1ea82c546ddd.png)

**Comment by syndenbock** [comment]
I will have to re-upgrade to the current version and recheck then.
