### ISSUE TITLE
Any update for 10.0?

### ISSUE THREAD

**Issue by FindingArrow** [alarofrunetotem/MailCommander#9]
Hi, Are you still playing wow? Any update for 10.0? Thanks.

**Comment by yad** [comment]
Hello I just provided a pull request 

https://github.com/alarofrunetotem/MailCommander/pull/10/files

**Comment by FindingArrow** [comment]
> Hello I just provided a pull request
> 
> https://github.com/alarofrunetotem/MailCommander/pull/10/files

Thanks a lot, I'll try it later.

**Comment by Araldwenn** [comment]
@yad : Thx a lot guy, I applied your changes and Mailcommander works now perfectly !

**Comment by banta84** [comment]
Not helped for me(( last working version before patch  was 1.1.6. No these strings at renewed lines at 1.1.6 so i try last release but not worked after changing in this 3 files.

**Comment by FindingArrow** [comment]
> Hello I just provided a pull request
> 
> https://github.com/alarofrunetotem/MailCommander/pull/10/files

Hi, Thanks for the update.
But I got something wrong with this addon.
1.The addon can't send items to the other faction characters.
2.When I have more than one character in the send list, the addon often send the items to the next character.
e.g.  
1.) I want to send meat to the warrior, fur to the hunter;
2.) I press [Send All] button.
3.) I got fur on my warrior.
[got](https://pinbox.oss-cn-beijing.aliyuncs.com/arrow/got.png)
[need_hunter](https://pinbox.oss-cn-beijing.aliyuncs.com/arrow/need_hunter.png)
[need_warrior](https://pinbox.oss-cn-beijing.aliyuncs.com/arrow/need_warrior.png)

Hope for the update. Thanks.

**Comment by QuinnyNZ** [comment]
Manually updated every line cos I am a nub with this and working. Thank you so much.

**Comment by yad** [comment]
Since 10.0.2 it needs these changes too :

https://github.com/alarofrunetotem/MailCommander/pull/11
https://github.com/alarofrunetotem/LibInit/pull/3/files

**Comment by QuinnyNZ** [comment]
Yeah, 10.0.2 has broken it again. Waits on the pull and thanks Yad and those working on this. Huge thank you to you all.
